### ISSUE TITLE
Forward/Backward pass size for DWaveNet

### ISSUE THREAD

**Issue by faber6911** [Sytronik/denoising-wavenet-pytorch#1]
Using your WaveNet implementation I have noticed that the output of ResidualConv1dGLU class generates an exaggerated forward / backward pass size, as seen from the output of torchsummary.
![image](https://user-images.githubusercontent.com/45421256/87539680-9f6bdc80-c69e-11ea-9b69-4f50ab86b9fd.png)
I tried to insert as a layer output a concatenated tensor instead of a tuple of tensors, and actually the size of the forward / backward pass reduces but still remains very high. 
![image](https://user-images.githubusercontent.com/45421256/87539874-fa9dcf00-c69e-11ea-9769-ef5d89da2831.png)
![image](https://user-images.githubusercontent.com/45421256/87539947-15704380-c69f-11ea-8077-aa1f6372179b.png)

Do you have any ideas on how to solve the problem or do you know what could be causing it?
The output is generated passing a 2 seconds audio with sr = 16000 in input to the Net, so is a tensor (1, 32000).

**Comment by Sytronik** [comment]
I haven't check how torchsummary calculates "Forward/backward pass size" and what that really means.
Have you check the torchsummary code?
I guess it's just a torchsummary's bug.
(I found torchsummary has a lot of bugs these days so I don't use it much.)

If you need to check how the model requires memory precisely,
you'd rather use a memory profiler like this: https://gist.github.com/dojoteef/26cd46f7cc38b38e6f443c5f62411aa3.

**Comment by faber6911** [comment]
Thanks for your feedback. I also immediately thought of a bug in torchsummary even if I don't understand why with other very large networks it doesn't give me these problems .. maybe it's due to the poor support of torch for 1d data.
Are you aware of a version of torchsummary less prone to this type of bugs?

**Comment by Sytronik** [comment]
Unfortunately, I don't know. I've  never given attention to the Forward/backward pass size. So I'm not sure whether specific version has that problem or all of the torchsummary version has that problem.
